TABLE = "table"
ARROW = "arrow"
TYPES = {"swimlane": TABLE, "Arrow": ARROW}
SOURCE = "source"
TARGET = "target"
ASSOCIATIONS = {"endarrow": TARGET, "startarrow": SOURCE}
IND_LONG_WORD_END = -3
IND_SHORT_WORD_END = -1
LONG_WORD_END = "ies"
SHORT_WORD_END = "ys"
PY_FILE_EXTENSION='py'